services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    ports: 
      - '6543:5432'
    volumes:
      - './postgresql-data:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_odoo
      - POSTGRESQL_DATABASE=bitnami_odoo
  odoo:
    image: docker.io/bitnami/odoo:16
    container_name: odoo16
    ports:
      - '80:8069'
    volumes:
      - './odoo-data:/bitnami/odoo'
      # Custom modules
      - './custom_addons:/bitnami/odoo/addons'
    depends_on:
      - postgresql
    environment:
    # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - ODOO_DATABASE_HOST=postgresql
      - ODOO_DATABASE_PORT_NUMBER=5432
      - ODOO_DATABASE_USER=bn_odoo
      - ODOO_DATABASE_NAME=bitnami_odoo
